import { useState } from "react";
import { G } from "@/lib/theme";
import { TODAY, TZ, WC_DAYS, SOCCER_PICKS, SUBTABS } from "@/lib/data";
import { Dot, Chip, Card, PBar } from "@/components/ui-primitives";
const FIELD_MAP: Record<string, string> = { over25: "pick", corners: "corners", handicap: "handicap", bookings: "bookings", draw: "draw", btts: "btts" };
export function SoccerPage() {
  const [sub, setSub] = useState("over25"); const active = SUBTABS.find((t) => t.key === sub)!; const field = FIELD_MAP[sub];
  const picks = SOCCER_PICKS.filter((p) => (p as any)[field]);
  return (<div style={{ padding: "28px 24px", maxWidth: 1060 }}>
    <div style={{ background: "linear-gradient(135deg,#0A1C35,#081428)", border: "1px solid rgba(0,229,255,.2)", borderRadius: 16, padding: "20px 24px", marginBottom: 22, display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 16 }}><div><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}><Dot c={G.accent} pulse /><span style={{ fontSize: 11, fontWeight: 700, color: G.accent, letterSpacing: 1 }}>FIFA WORLD CUP 2026 · {WC_DAYS} DAYS TO KICK-OFF</span></div><div style={{ fontSize: 26, fontWeight: 900, marginBottom: 4 }}>⚽ Soccer Betting Hub</div><div style={{ color: G.dim, fontSize: 13 }}>Real fixtures · {TODAY} · All times {TZ}</div></div><div style={{ textAlign: "center" }}><div style={{ fontSize: 48, fontWeight: 900, color: G.accent, fontFamily: "monospace", lineHeight: 1 }}>{WC_DAYS}</div><div style={{ fontSize: 11, color: G.dim, fontWeight: 700 }}>DAYS TO WC</div></div></div>
    <Card style={{ marginBottom: 20, padding: 18 }}><div style={{ fontSize: 13, fontWeight: 700, color: G.dim, marginBottom: 12, letterSpacing: 1 }}>TODAY'S FIXTURES · {TODAY}</div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(240px,1fr))", gap: 10 }}>{SOCCER_PICKS.map((f) => (<div key={f.id} style={{ background: G.bg, border: `1px solid ${G.border}`, borderRadius: 10, padding: "12px 14px", display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontSize: 10, color: G.muted, marginBottom: 3 }}>{f.league}</div><div style={{ fontWeight: 700, fontSize: 13 }}>{f.home} vs {f.away}</div></div><div style={{ fontFamily: "monospace", fontWeight: 700, color: G.gold, flexShrink: 0, marginLeft: 8 }}>{f.time}</div></div>))}</div></Card>
    <div style={{ display: "flex", gap: 7, flexWrap: "wrap", marginBottom: 18 }}>{SUBTABS.map((t) => (<button key={t.key} onClick={() => setSub(t.key)} style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${sub === t.key ? G.accent : G.border}`, background: sub === t.key ? G.accent : "transparent", color: sub === t.key ? "#000" : G.dim, fontFamily: "inherit", fontSize: 13, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", gap: 6 }}>{t.icon} {t.label} <span style={{ background: sub === t.key ? "rgba(0,0,0,.2)" : "rgba(0,229,255,.1)", color: sub === t.key ? "#000" : G.accent, borderRadius: 4, padding: "1px 6px", fontSize: 10, fontWeight: 800 }}>{picks.length}</span></button>))}</div>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(330px,1fr))", gap: 16 }}>{picks.map((p, i) => { const val = (p as any)[field]; return (<div key={p.id} className="fu" style={{ background: G.card2, border: `1px solid ${G.border}`, borderLeft: `3px solid ${G.accent}`, borderRadius: 14, padding: 18, animationDelay: `${i * 0.07}s` }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }}><div style={{ flex: 1 }}><div style={{ display: "flex", gap: 6, marginBottom: 6, flexWrap: "wrap" }}><Chip color={p.tag === "SHARP" ? G.green : G.accent} bg={p.tag === "SHARP" ? "rgba(0,255,136,.1)" : "rgba(0,229,255,.1)"}>{p.tag}</Chip><span style={{ fontSize: 11, color: G.dim }}>{p.league}</span></div><div style={{ fontWeight: 800, fontSize: 16 }}>{p.home} <span style={{ color: G.muted, fontWeight: 400, fontSize: 13 }}>vs</span> {p.away}</div></div><div style={{ textAlign: "right", marginLeft: 12, flexShrink: 0 }}><div style={{ fontFamily: "monospace", fontSize: 22, fontWeight: 700, color: G.accent }}>{p.odds}</div><div style={{ fontSize: 11, color: G.dim }}>{p.units}u</div></div></div><div style={{ background: G.bg, borderRadius: 8, padding: "10px 12px", marginBottom: 10, border: `1px solid ${G.border}` }}><div style={{ fontSize: 10, color: G.muted, fontWeight: 700, marginBottom: 4 }}>PICK</div><div style={{ fontFamily: "monospace", fontWeight: 700, color: G.accent, fontSize: 13 }}>{val}</div></div><PBar v={p.prob} c={G.accent} /></div>); })}</div>
  </div>); }